namespace Json2BakinPlugin.Models
{
    public static class CountDownTimer
    {
        public static string WriteCommonEvent()
        {
            return "Guid\t00000000-0000-0000-0000-000000000000\n" +
"イベント名\tカウントダウンタイマー\n" +
"シート\tInitialize\n" +
"\tグラフィック\t00000000-0000-0000-0000-000000000000\n" +
"\t向き\t\t1\n" +
"\t向き固定\tFalse\n" +
"\t物理\tFalse\n" +
"\t衝突判定\tFalse\n" +
"\tイベントと衝突\tTrue\n" +
"\t移動速度\t0\n" +
"\t移動頻度\t0\n" +
"\t移動タイプ\tNONE\n" +
"\t押せる\tTrue\n" +
"\tスクリプト\n" +
"\t\t開始条件\tAUTO\n" +
"\t\t高さ無視\tFalse\n" +
"\t\t判定拡張\tFalse\n" +
"\t\tコマンド\tVARIABLE\n" +
"\t\t\t整数\t0\n" +
"\t\t\t変数\tN:TimerInfo\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSWITCH\n" +
"\t\t\t変数\tN:TimerTrigger\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\tスクリプト終了\n" +
"シート終了\n" +
"シート\tWait\n" +
"\tグラフィック\t00000000-0000-0000-0000-000000000000\n" +
"\t向き\t1\n" +
"\t向き固定\tFalse\n" +
"\t物理\tFalse\n" +
"\t衝突判定\tFalse\n" +
"\tイベントと衝突\tTrue\n" +
"\t移動速度\t0\n" +
"\t移動頻度\t0\n" +
"\t移動タイプ\tNONE\n" +
"\t押せる\tTrue\n" +
"\t条件\tCOND_TYPE_SWITCH\n" +
"\t\t比較演算子\tEQUAL\n" +
"\t\tインデックス\t-1\n" +
"\t\tオプション\t0\n" +
"\t\tローカル参照\tFalse\n" +
"\t\t参照名\tTimerTrigger\n" +
"\t条件終了\n" +
"\tスクリプト\n" +
"\t\t開始条件\tNONE\n" +
"\t\t高さ無視\tFalse\n" +
"\t\t判定拡張\tFalse\n" +
"\tスクリプト終了\n" +
"シート終了\n" +
"シート\tCountdown\n" +
"\tグラフィック\t00000000-0000-0000-0000-000000000000\n" +
"\t向き\t1\n" +
"\t向き固定\tFalse\n" +
"\t物理\tFalse\n" +
"\t衝突判定\tFalse\n" +
"\tイベントと衝突\tTrue\n" +
"\t移動速度\t0\n" +
"\t移動頻度\t0\n" +
"\t移動タイプ\tNONE\n" +
"\t押せる\tTrue\n" +
"\t条件\tCOND_TYPE_VARIABLE\n" +
"\t\t比較演算子\tEQUAL_GREATER\n" +
"\t\tインデックス\t-1\n" +
"\t\tオプション\t0\n" +
"\t\tローカル参照\tFalse\n" +
"\t\t参照名\tTimerInfo\n" +
"\t条件終了\n" +
"\t条件\t COND_TYPE_SWITCH\n" +
"\t\t比較演算子\tEQUAL\n" +
"\t\tインデックス\t-1\n" +
"\t\tオプション\t0\n" +
"\t\tローカル参照\tFalse\n" +
"\t\t参照名\tTimerTrigger\n" +
"\t条件終了\n" +
"\tスクリプト\n" +
"\t\t開始条件\tPARALLEL\n" +
"\t\t高さ無視\tFalse\n" +
"\t\t判定拡張\tFalse\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t変数\t N:TimerInfo\n" +
"\t\t\t整数\t6000\n" +
"\t\t\t整数\t1\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t100\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t9\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t101\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t40\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t9\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t102\n" +
"\t\t\tGuid\t878766cd-1d17-44e4-83be-5ff891c490a3\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t70\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t103\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t5\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t104\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t140\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t9\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tHLVARIABLE\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t65536\n" +
"\t\t\t整数\t2\n" +
"\t\t\t変数\tN:TimerInfo\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tHLVARIABLE\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t65537\n" +
"\t\t\t整数\t2\n" +
"\t\t\t変数\tN:TimerInfo\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tHLVARIABLE\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t65538\n" +
"\t\t\t整数\t2\n" +
"\t\t\t変数\tN:TimerInfo\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tHLVARIABLE\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t65539\n" +
"\t\t\t整数\t2\n" +
"\t\t\t変数\tN:TimerInfo\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tVARIABLE\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t65536\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t60\n" +
"\t\t\t整数\t4\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tHLVARIABLE\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t65536\n" +
"\t\t\t整数\t2\n" +
"\t\t\t整数\t65536\n" +
"\t\t\t整数\t7\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tVARIABLE\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t65536\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t10\n" +
"\t\t\t整数\t4\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tHLVARIABLE\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t65536\n" +
"\t\t\t整数\t2\n" +
"\t\t\t整数\t65536\n" +
"\t\t\t整数\t7\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tVARIABLE\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t65537\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t60\n" +
"\t\t\t整数\t4\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tHLVARIABLE\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t65537\n" +
"\t\t\t整数\t2\n" +
"\t\t\t整数\t65537\n" +
"\t\t\t整数\t7\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tHLVARIABLE\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t65537\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t10\n" +
"\t\t\t整数\t6\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tHLVARIABLE\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t65538\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t60\n" +
"\t\t\t整数\t6\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tVARIABLE\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t65538\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t10\n" +
"\t\t\t整数\t4\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tHLVARIABLE\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t65538\n" +
"\t\t\t整数\t2\n" +
"\t\t\t整数\t65538\n" +
"\t\t\t整数\t7\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tHLVARIABLE\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t65539\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t60\n" +
"\t\t\t整数\t6\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tHLVARIABLE\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t65539\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t10\n" +
"\t\t\t整数\t6\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65536\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t100\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65536\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t100\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65536\n" +
"\t\t\t整数\t2\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t100\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t2\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65536\n" +
"\t\t\t整数\t3\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t100\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t3\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65536\n" +
"\t\t\t整数\t4\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t100\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t4\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65536\n" +
"\t\t\t整数\t5\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t100\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t5\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65536\n" +
"\t\t\t整数\t6\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t100\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t6\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65536\n" +
"\t\t\t整数\t7\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t100\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t7\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65536\n" +
"\t\t\t整数\t8\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t100\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t8\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65536\n" +
"\t\t\t整数\t9\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t100\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t9\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65537\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t101\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t40\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65537\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t101\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t40\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65537\n" +
"\t\t\t整数\t2\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t101\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t40\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t2\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65537\n" +
"\t\t\t整数\t3\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t101\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t40\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t3\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65537\n" +
"\t\t\t整数\t4\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t101\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t40\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t4\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65537\n" +
"\t\t\t整数\t5\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t101\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t40\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t5\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65537\n" +
"\t\t\t整数\t6\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t101\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t40\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t6\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65537\n" +
"\t\t\t整数\t7\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t101\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t40\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t7\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65537\n" +
"\t\t\t整数\t8\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t101\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t40\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t8\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65537\n" +
"\t\t\t整数\t9\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t101\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t40\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t9\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t102\n" +
"\t\t\tGuid\t878766cd-1d17-44e4-83be-5ff891c490a3\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t70\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65538\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t103\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65538\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t103\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65538\n" +
"\t\t\t整数\t2\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t103\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t2\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65538\n" +
"\t\t\t整数\t3\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t103\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t3\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65538\n" +
"\t\t\t整数\t4\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t103\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t4\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65538\n" +
"\t\t\t整数\t5\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t103\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t5\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65538\n" +
"\t\t\t整数\t6\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t103\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t6\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65538\n" +
"\t\t\t整数\t7\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t103\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t7\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65538\n" +
"\t\t\t整数\t8\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t103\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t8\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65538\n" +
"\t\t\t整数\t9\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t103\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t9\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65539\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t104\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t140\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65539\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t104\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t140\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65539\n" +
"\t\t\t整数\t2\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t104\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t140\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t2\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65539\n" +
"\t\t\t整数\t3\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t104\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t140\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t3\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65539\n" +
"\t\t\t整数\t4\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t104\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t140\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t4\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65539\n" +
"\t\t\t整数\t5\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t104\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t140\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t5\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65539\n" +
"\t\t\t整数\t6\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t104\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t140\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t6\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65539\n" +
"\t\t\t整数\t7\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t104\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t140\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t7\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65539\n" +
"\t\t\t整数\t8\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t104\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t140\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t8\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t整数\t65539\n" +
"\t\t\t整数\t9\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPPICTURE\n" +
"\t\t\t整数\t104\n" +
"\t\t\tGuid\t564e5b14-aa66-4ad1-bb01-210da74ad404\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t-1\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t140\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t9\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tWAIT\n" +
"\t\t\t整数\t1000\n" +
"\t\t\t整数\t1\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tIFVARIABLE\n" +
"\t\t\t変数\tN:TimerInfo\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPHIDE\n" +
"\t\t\t整数\t100\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPHIDE\n" +
"\t\t\t整数\t101\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPHIDE\n" +
"\t\t\t整数\t102\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPHIDE\n" +
"\t\t\t整数\t103\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tSPHIDE\n" +
"\t\t\t整数\t104\n" +
"\t\t\t整数\t0\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tELSE\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tENDIF\n" +
"\t\tコマンド終了\n" +
"\t\tコマンド\tVARIABLE\n" +
"\t\t\t整数\t0\n" +
"\t\t\t変数\tN:TimerInfo\n" +
"\t\t\t整数\t0\n" +
"\t\t\t整数\t1\n" +
"\t\t\t整数\t2\n" +
"\t\tコマンド終了\n" +
"\tスクリプト終了\n" +
"シート終了\n";
        }
    }
}